name: lint-test-deploy
on: push
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm test
      - name: Run Build
        run: npm build
      - name: Run Test
        run: npm test
  
    
  
  Deploy:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci 
        - name: Build Project
          run: npm run build
        - name: Deploy 
          run: echo "deploy"